#pragma once

#define TINY_ASIO_BUFFER_INT	0
#define TINY_ASIO_BUFFER_FLOAT	1

/**
* TINY_ASIO_BUFFER_OPTION‚É‘Î‚µ‚ÄC”CˆÓ‚ÌTINY_ASIO_BUFFER_Œ^–¼‚ðŠ„‚è“–‚Ä‚é‚±‚Æ‚ÅC
* TINY_ASIO_BUFFER_TYPE‚ÌŒ^‚ðŒˆ‚ß‚ç‚ê‚é‚æ‚¤‚É‚µ‚Ä‚¢‚é
*/
#define TINY_ASIO_BUFFER_OPTION TINY_ASIO_BUFFER_FLOAT

#if TINY_ASIO_BUFFER_OPTION == TINY_ASIO_BUFFER_INT
#define TINY_ASIO_BUFFER_TYPE int
#elif TINY_ASIO_BUFFER_OPTION == TINY_ASIO_BUFFER_FLOAT
#define TINY_ASIO_BUFFER_TYPE float
#endif